### ISSUE TITLE
slow go-get because of aclindsa/go dep

### ISSUE THREAD

**Issue by maxhawkins** [aclindsa/ofxgo#1]
Thanks for releasing this library.

I'm excited to use it, but it's taking a long time to download. `go get` is getting stuck on downloading aclindsa/go, which seems to be a big repo.

Is it possible to use the default Go encoding/xml or put a fork in a smaller git repo?

**Comment by aclindsa** [comment]
Unfortunately it isn't possible to use the default encoding/xml (see https://github.com/golang/go/issues/19506 and the top two commits at https://github.com/aclindsa/go/commits/master). Basically, OFX's SGML is broken and the upstream Go folks don't want to add a strange new part of their API just to make their encoding/xml parser handle something that isn't even XML.

It does seem possible to make it a smaller repo, however. The one downside is that it'll be a little more of a pain to rebase to pull in upstream changes while maintaining git history if I chop that subdirectory out of the main go repo. I'll also need to look into what I'll need to do to obey the go license terms when I do this (for instance, I'm sure I'll need to at least copy the license over).

**Comment by aclindsa** [comment]
This should be fixed in https://github.com/aclindsa/ofxgo/commit/fa05f64497f4bdc51fce2f668e8123a96a035fa3 by adding https://github.com/aclindsa/xml

I tested this and everything seems to work well for me, but feel free to re-open this if you encounter any problems.

**Comment by maxhawkins** [comment]
Thanks!
