### ISSUE TITLE
BMO produces invalid XML for BANKMSGSETV1

### ISSUE THREAD

**Issue by mkobetic** [aclindsa/ofxgo#15]
Bank of Montreal (BMO) allows downloads of multiple accounts at once. It uses BANKMSGSETV1 element for that (with embedded BANKMSGSET inside it for some reason), but it emits start elements instead of end elements at the end 🤦‍♂️ . 

```
OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:NONE

<OFX>
<SIGNONMSGSRSV1>
<SONRS>
<STATUS>
<CODE>0
<SEVERITY>INFO
<MESSAGE>OK
</STATUS>
<DTSERVER>20181228000224.466[-5:EDT]
<USERKEY>329402394029374
<LANGUAGE>ENG
<INTU.BID>00001
</SONRS>
</SIGNONMSGSRSV1>
<BANKMSGSETV1><BANKMSGSET>
<BANKMSGSRSV1>

<STMTTRNRS>
...
</STMTTRNRS>

</BANKMSGSRSV1>
<BANKMSGSET><BANKMSGSETV1>
</OFX>
```

It seems that the library currently doesn't support MSGSET elements at all, but even if it did the end elements would still be a problem. I could get the file through by making response parsing ignore MSGSET elements completely, as follows:

```
@@ -356,7 +357,13 @@ func ParseResponse(reader io.Reader) (*Response, error) {
                        return nil, err
                } else if ofxEnd, ok := tok.(xml.EndElement); ok && ofxEnd.Name.Local == "OFX" {
                        return &or, nil // found closing XML element, so we're done
+               } else if ofxEnd, ok := tok.(xml.EndElement); ok && strings.Contains(ofxEnd.Name.Local, "MSGSET") {
+                       continue // ignore MSGSET elements
                } else if start, ok := tok.(xml.StartElement); ok {
+                       // ignore MSGSET elements
+                       if strings.Contains(start.Name.Local, "MSGSET") {
+                               continue
+                       }
                        slice, ok := messageSlices[start.Name.Local]
                        if !ok {
                                return nil, errors.New("Invalid message set: " + start.Name.Local)
``` 
Note that I had to ignore EndElements as well, to allow the parser to unwind its element stack properly. The way the sample above is parsed is as if there are two sets of MSGSET elements nested in each other and the end elements get injected from the parser stack when it encounters the closing OFX element. 

Anyway, I admit that this is outright disgusting, but it does seem to allow processing the file correctly including multiple account message sets. I absolutely understand if this is too much of a hack to allow in. I can muscle my way through outside of the ofxgo library if needed (just use some `grep -v MSGSET` equivalent), but I figured I'd bring it up anyway.

**Comment by mkobetic** [comment]
Ironically, bank account downloads don't seem to have the #14 problems, go figure 🤷‍♂️

**Comment by aclindsa** [comment]
Yikes. I'm reviewing the OFX spec now and am more confused than when I started looking at this. In addition to the issues you noted with start elements where end elements should be:
1. `<BANKMSGSET>` should contain `<BANKMSGSETV1>`, not the other way around.
2. Neither `<BANKMSGSET>` nor `<BANKMSGSETV1>` should contain `<BANKMSGSRSV1>` (either directly or indirectly)
3. `<BANKMSGSET>` is only supposed to be contained in the `<MSGSETLIST>` tag in a a Profile Response, `<PROFRS>`. It is used to indicate which OFX banking features your bank's implementation provides, and has nothing to do with actually providing you with your account's statement...

This violates the spec quite creatively in more ways than I would've thought possible for only having added four tags. Out of morbid curiosity, have you been able to parse this file with any other programs or libraries?

In my opinion, this is beyond broken to the point that your bank really ought to fix it, and I don't see a great way to modify the shared internals of ofxgo to support it. That said, one thing we could do is to write a bmo_client.go which implements the Client interface. Most methods could be the standard ones, but its Request method would need to be modified to look like the current contents of clientRequest, except to call a modified ParseResponse() method which contains your hack above to ignore these elements. You would then have to explicitly use this client when parsing OFX files from this bank, but it wouldn't pollute that parsing code for everyone.

What do you think?

**Comment by mkobetic** [comment]
OK, that's worse than I thought. [These comments](https://github.com/aclindsa/ofxgo/blob/master/response.go#L20) lead me to think that MSGSETs are more prominent (maybe optional for single set). If they are so obscure, then I'd say it's not worth making special concessions to output that's broken so severely.

**Comment by aclindsa** [comment]
Oops, sorry those comments were confusing. The documentation refers to each unique category of message as a "message set", so I grouped them the same way. The comments are of the elements which describe the capabilities and version of the set since they were named appropriately, but in hindsight that might not have been the best idea.

I'll leave it up to you whether we try to go for this or make a kludge that will get you back in business. I feel a little less dirty if the kludge is in its own file without affecting the main parsing code, so I'm okay with that.

**Comment by mkobetic** [comment]
It seems that the way the elements are used in the BMO output is completely wrong so I'd say it's not worth polluting the library with this nonsense. As i mentioned, fortunately I can simply filter those elements out outside of the library so there's not need to do it for my sake.

**Comment by aclindsa** [comment]
Sounds good. Let me know if you find anything else!
