### ISSUE TITLE
"Windows" new line required for some banks

### ISSUE THREAD

**Issue by JohnStarich** [aclindsa/ofxgo#17]
It looks like some banks, like USAA, don't support standard unix line endings `\n`:

```
OFXAdapter: Failed to parse request: Unable to parse an atomic field "OFXRequest.Headers.OFXHeader": unable to find end delimiters "
".
```

Looking around, I found this issue which solved the problem by adding `\r`: https://github.com/euforic/banking.js/issues/8

Based on the code in the python `ofxclient` library, it looks like using `\r\n` works for all banks: https://github.com/captin411/ofxclient/blob/v2.0.4/ofxclient/client.py#L25

In my custom client, I've hacked around the problem with this line:

```go
var r *ofxgo.Request
b, _ := r.Marshal()
b = bytes.NewBuffer(bytes.Replace(b.Bytes(), []byte{'\n'}, []byte{'\r', '\n'}, -1))
```

What are your thoughts on changing the line ending for all requests? If you like I can try my hand at a PR too 😄

**Comment by aclindsa** [comment]
I think I'm okay with this in principle (though I'd like to do a little sanity check of my own that a few common banks continue to work after the change).

Is the "OFXAdapter: Failed to parse request..." message you're getting a straight response from USAA, or are you using some other piece of software to intermediate?

**Comment by JohnStarich** [comment]
Ok cool 😄 Yeah, makes sense! It seems to work with 2 of my credit cards and both of my USAA accounts

That's directly from USAA, I'm pretty sure. That line appears above the OFX headers but after the HTTP headers in the raw response. (I had a similar, but different message when I passed closing tags in my other issue #18)

**Comment by aclindsa** [comment]
> That's directly from USAA, I'm pretty sure.

Ah, okay. The name "OFXAdapter" made me think you might be using something in the middle to try to make it behave.

I'd welcome a PR for this. My initial thoughts are that it would require both a change to the XML library (see https://github.com/aclindsa/xml/blob/207ec7fb74201d07016cbd7064cb6331dde91eba/marshal.go#L962) and where ofxgo writes the SGML header: https://github.com/aclindsa/xml/blob/207ec7fb74201d07016cbd7064cb6331dde91eba/marshal.go#L962. There may be a few other places sprinkled around that I haven't discovered yet that you'll find during testing!

I think ideally which line ending to use would be a runtime-configurable parameter, and not a hard-coded thing (in both the xml and ofxgo libraries).

**Comment by JohnStarich** [comment]
Sounds good 👍 thanks for the tips!
I like the config parameter idea. It seems like `\r\n` line-endings are compatible with more institutions, so I think it would make a good default value, then this parameter could let you switch to unix line-endings if necessary?

I'll be out of town next week, but I'll probably give it a shot the week after 🌴

**Comment by aclindsa** [comment]
> It seems like `\r\n` line-endings are compatible with more institutions

Is your basis for this that the two projects you mentioned above do it that way, or have you found other info? I think the projects are probably sufficient evidence, but I'm curious to learn more if you came across other sources...

**Comment by JohnStarich** [comment]
Sorry about my delay in getting back to you!

I based that on those projects I mentioned, and they appear to have a little traction based on their GitHub stats. It isn't really much to go on, I haven't done much research in this area 😉 
Based on my brief searches (best one seems to be `"ofx" carriage return`), this issue does seem to pop up on forums and in a few libraries

**Comment by aclindsa** [comment]
No worries - life happens.

Thanks for the reply - my opinion is that we shouldn't let lack of an authoritative source stop us from moving forward (though I can still hope for one!).

**Comment by JohnStarich** [comment]
First PR is ready to go! https://github.com/aclindsa/xml/pull/2

**Comment by JohnStarich** [comment]
friendly poke 👉 @aclindsa

**Comment by aclindsa** [comment]
@JohnStarich Well-deserved pokes, to be sure. Sorry about the delay - unfortunately you lost the latency lottery and sent these when I'm busier than I've been in a while. I have not forgotten about them, though, and hope to review them this week!

**Comment by JohnStarich** [comment]
Oh no! 😆

No rush, just wanted to make sure you weren’t asleep at the wheel! I’ve got work-arounds for now, anyway 😉

**Comment by JohnStarich** [comment]
Second part is up now too, for extra fun 💥 https://github.com/aclindsa/ofxgo/pull/20
