### ISSUE TITLE
Unable to connect to any of my banks using this

### ISSUE THREAD

**Issue by ldrrp** [aclindsa/ofxgo#21]
query.URL = "https://www.oasis.cfree.com/fip/genesis/prod/02601.ofx"
	query.Signon.Org = ofxgo.String("ISC")
	query.Signon.Fid = ofxgo.String("2601")

I keep getting no bank messages received using the example. with my credentials and bank id and acctid in place.

**Comment by aclindsa** [comment]
Unfortunately, there are a myriad of reasons this may not be working. I'm going to list a few suggestions of places to start based on my experience. If none of these pan out, we can dig deeper:

- Have you tried using the included command-line client (see the bottom of the README)? It has a mode where it will sweep through a variety of client IDs and other parameters. Some banks require very specific values for these
- Have you successfully downloaded OFX transactions from your bank using another piece of software?
- Have you tried limiting the date to the last week or month? Some banks return empty transactions if you leave off dates or have too large of a date range.
- Have you set a ClientUID? Some banks require this, and some banks will make you login to confirm it every time you add a new ID.

**Comment by aclindsa** [comment]
I'm closing this issue since it's been a while without a response. Please feel free to re-open this issue if you'd still like to continue this conversation.
