### ISSUE TITLE
Is There List of Finance Institution Tested

### ISSUE THREAD

**Issue by nirajbhatt7** [aclindsa/ofxgo#26]
Is there a list maintained somewhere for all the finance institutions that are tested with this library?

**Comment by aclindsa** [comment]
I have not attempted to keep such a list - at least in part because I don't have the time to maintain it, so it would quickly become out-of-date with all the 'quirks' that different financial institutions seem to always be introducing.

**Comment by JohnStarich** [comment]
If you're looking for which institutions support OFX, I usually refer to this site: https://www.ofxhome.com/index.php/home/directory

Some of those institutions no longer work, but it's generally a pretty great source for connection details.

**Comment by nirajbhatt7** [comment]
Thanks for the prompt response. It makes sense.
